package br.com.zumbolovsky.fateapp.config.error

object ErrorMessages {
    const val UNKNOWN = "UNKNOWN"
    const val MESSAGE_NOT_READABLE = "MESSAGE.NOT.READABLE"
    const val ARGUMENT_NOT_VALID = "ARGUMENT.NOT.VALID"
    const val ENTITY_NOT_FOUND_DEFAULT = "ENTITY.NOT.FOUND.DEFAULT"
    const val ENTITY_NOT_FOUND = "ENTITY.NOT.FOUND"
    const val ENTITY_EXISTS_DEFAULT = "ENTITY.EXISTS.DEFAULT"
    const val ENTITY_EXISTS = "ENTITY.EXISTS"
    const val UNAUTHORIZED = "UNAUTHORIZED"
    const val IMPLEMENTATION_NOT_FOUND = "IMPLEMENTATION.NOT.FOUND"
    const val INTERNAL_ERROR = "INTERNAL.ERROR"
    const val USER_ALREADY_SIGNED_IN = "USER.ALREADY.SIGNED.IN"
    const val USER = "USER"
    const val ADMIN_ROLE = "ADMIN.ROLE"
    const val USER_ROLE = "USER.ROLE"
}